# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-28 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=200)),
                ('tz', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='activityperiod',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.User'),
        ),
    ]
